title: Kayla Smith CEAMLS SAIRI Website Summer 2024 
logo: kaylasmith.headshot.jpeg
description: Hi! My name is Kayla Smith and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
